### ISSUE TITLE
404 when open a post link

### ISSUE THREAD

**Issue by vincenzopalazzo** [importantimport/urara#83]
Searching for a link will return in a 404

I am trying to access the following post https://blog.hedwing.dev/ln/lnprototest/lnprototest_intro_1ofn/ but the result is 404 

but if I navigate from https://blog.hedwing.dev I can open the post with no problem

**Comment by Interstellar750** [comment]
I've tested it as you described and it will return a 404, all the articles have this problem

But your Urara is outdated, can you provide the commit SHA when you started building the site based on this template?

If you don't keep a commit log, you can also provide me with the `pnpm-lock.yaml` file and I'll try to find out which version you're using

**Comment by kwaa** [comment]
Can you try updating Urara to the latest version?

**Comment by vincenzopalazzo** [comment]
Looks like that with the recent version netfly fails with 

```
12:31:53 PM: vite v5.4.5 building SSR bundle for production...
12:31:53 PM: transforming...
12:31:53 PM: ✓ 2 modules transformed.
12:31:53 PM: x Build failed in 40ms
12:31:53 PM: error during build:
12:31:53 PM: [vite-plugin-pwa:build] [plugin vite-plugin-svelte] src/routes/+layout.svelte (11:14): /opt/build/repo/src/routes/+layout.svelte:11:14 Unexpected token
12:31:53 PM: file: /opt/build/repo/src/routes/+layout.svelte:11:14
12:31:53 PM: 
12:31:53 PM:   9 |    import { registerSW } from 'virtual:pwa-register'
12:31:53 PM:  10 |
12:31:53 PM:  11 |    import type { LayoutData } from './$types'
12:31:53 PM:                      ^
12:31:53 PM:  12 |
12:31:53 PM:  13 |    import 'uno.css'
12:31:53 PM: 
12:31:53 PM: ParseError: Unexpected token
12:31:53 PM:     at error (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/utils/error.js:56:16)
12:31:53 PM:     at Parser.error (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:143:3)
12:31:53 PM:     at Parser.acorn_error (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:130:8)
12:31:53 PM:     at Object.read_script [as read] (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/read/script.js:50:10)
12:31:53 PM:     at tag (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/state/tag.js:203:27)
12:31:53 PM:     at new Parser (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:91:12)
12:31:53 PM:     at parse (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:268:17)
12:31:53 PM:     at Module.compile (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/compile/index.js:136:14)
12:31:53 PM:     at compileSvelte (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.19_vite@5.4.5_@types+node@20.16.5_lightningcss@1.27.0_terser@5.32.0_/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:140:22)
12:31:53 PM:     at async Object.transform (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.19_vite@5.4.5_@types+node@20.16.5_lightningcss@1.27.0_terser@5.32.0_/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:152:20)
12:31:53 PM:     at async transform (file:///opt/build/repo/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:18831:16)
12:31:53 PM:     at async ModuleLoader.addModuleSource (file:///opt/build/repo/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:19047:36)
12:31:53 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
12:31:53 PM: ERROR: "kit:build" exited with 1.
12:31:53 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
12:31:53 PM: ​
12:31:53 PM: "build.command" failed                                        
12:31:53 PM: ────────────────────────────────────────────────────────────────
12:31:53 PM: ​
12:31:53 PM:   Error message
12:31:53 PM:   Command failed with exit code 1: NETLIFY=true npx pnpm build (https://ntl.fyi/exit-code-1)
12:31:53 PM: ​
12:31:53 PM:   Error location
12:31:53 PM:   In build.command from netlify.toml:
12:31:53 PM:   NETLIFY=true npx pnpm build
12:31:53 PM: ​
12:31:53 PM:   Resolved config
12:31:53 PM:   build:
12:31:53 PM:     command: NETLIFY=true npx pnpm build
12:31:53 PM:     commandOrigin: config
12:31:53 PM:     environment:
12:31:53 PM:       - REVIEW_ID
12:31:53 PM:       - NPM_FLAGS
12:31:53 PM:     publish: /opt/build/repo/build
12:31:53 PM:     publishOrigin: config
12:31:53 PM:   functions:
12:31:53 PM:     '*':
12:31:53 PM:       node_bundler: esbuild
12:31:53 PM:   functionsDirectory: /opt/build/repo/netlify/functions
12:31:54 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
12:31:54 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
12:31:54 PM: Failing build: Failed to build site
12:31:54 PM: Finished processing build request in 37.993s
```

Any idea on how to solve this?

**Comment by nuckle** [comment]
> Looks like that with the recent version netfly fails with
> 
> ```
> 12:31:53 PM: vite v5.4.5 building SSR bundle for production...
> 12:31:53 PM: transforming...
> 12:31:53 PM: ✓ 2 modules transformed.
> 12:31:53 PM: x Build failed in 40ms
> 12:31:53 PM: error during build:
> 12:31:53 PM: [vite-plugin-pwa:build] [plugin vite-plugin-svelte] src/routes/+layout.svelte (11:14): /opt/build/repo/src/routes/+layout.svelte:11:14 Unexpected token
> 12:31:53 PM: file: /opt/build/repo/src/routes/+layout.svelte:11:14
> 12:31:53 PM: 
> 12:31:53 PM:   9 |    import { registerSW } from 'virtual:pwa-register'
> 12:31:53 PM:  10 |
> 12:31:53 PM:  11 |    import type { LayoutData } from './$types'
> 12:31:53 PM:                      ^
> 12:31:53 PM:  12 |
> 12:31:53 PM:  13 |    import 'uno.css'
> 12:31:53 PM: 
> 12:31:53 PM: ParseError: Unexpected token
> 12:31:53 PM:     at error (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/utils/error.js:56:16)
> 12:31:53 PM:     at Parser.error (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:143:3)
> 12:31:53 PM:     at Parser.acorn_error (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:130:8)
> 12:31:53 PM:     at Object.read_script [as read] (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/read/script.js:50:10)
> 12:31:53 PM:     at tag (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/state/tag.js:203:27)
> 12:31:53 PM:     at new Parser (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:91:12)
> 12:31:53 PM:     at parse (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/parse/index.js:268:17)
> 12:31:53 PM:     at Module.compile (file:///opt/build/repo/node_modules/.pnpm/svelte@4.2.19/node_modules/svelte/src/compiler/compile/index.js:136:14)
> 12:31:53 PM:     at compileSvelte (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.19_vite@5.4.5_@types+node@20.16.5_lightningcss@1.27.0_terser@5.32.0_/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:140:22)
> 12:31:53 PM:     at async Object.transform (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.19_vite@5.4.5_@types+node@20.16.5_lightningcss@1.27.0_terser@5.32.0_/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:152:20)
> 12:31:53 PM:     at async transform (file:///opt/build/repo/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:18831:16)
> 12:31:53 PM:     at async ModuleLoader.addModuleSource (file:///opt/build/repo/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:19047:36)
> 12:31:53 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
> 12:31:53 PM: ERROR: "kit:build" exited with 1.
> 12:31:53 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
> 12:31:53 PM: ​
> 12:31:53 PM: "build.command" failed                                        
> 12:31:53 PM: ────────────────────────────────────────────────────────────────
> 12:31:53 PM: ​
> 12:31:53 PM:   Error message
> 12:31:53 PM:   Command failed with exit code 1: NETLIFY=true npx pnpm build (https://ntl.fyi/exit-code-1)
> 12:31:53 PM: ​
> 12:31:53 PM:   Error location
> 12:31:53 PM:   In build.command from netlify.toml:
> 12:31:53 PM:   NETLIFY=true npx pnpm build
> 12:31:53 PM: ​
> 12:31:53 PM:   Resolved config
> 12:31:53 PM:   build:
> 12:31:53 PM:     command: NETLIFY=true npx pnpm build
> 12:31:53 PM:     commandOrigin: config
> 12:31:53 PM:     environment:
> 12:31:53 PM:       - REVIEW_ID
> 12:31:53 PM:       - NPM_FLAGS
> 12:31:53 PM:     publish: /opt/build/repo/build
> 12:31:53 PM:     publishOrigin: config
> 12:31:53 PM:   functions:
> 12:31:53 PM:     '*':
> 12:31:53 PM:       node_bundler: esbuild
> 12:31:53 PM:   functionsDirectory: /opt/build/repo/netlify/functions
> 12:31:54 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
> 12:31:54 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
> 12:31:54 PM: Failing build: Failed to build site
> 12:31:54 PM: Finished processing build request in 37.993s
> ```
> 
> Any idea on how to solve this?

Just tried to deploy it with netlify and it works fine (on the latest version at least)

<details>
  <summary>Result</summary>
  <img src="https://github.com/user-attachments/assets/c86746f6-12ac-43b4-8ded-29a014300007" alt="result">
</details>

**Comment by vincenzopalazzo** [comment]
Ok rebuild from the main, and now it is working https://blog.hedwig.sh/ln/lnprototest/lnprototest_intro_1ofn/

P.S: Just for context I changed also from netfly to cloudflare, this should not make an impact but I would like to just point out
